server:
  port: 8010
age: 18
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/1808a?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: root
  redis:
    port: 6379
    host: localhost
  rabbitmq:
    port: 5672
    username: root
    password: root
    host: localhost
mybatis:
   mapper-locations: classpath:mybatis/*Mapper.xml

logging:
  path: C:\Users\lenovo\logging
  level:
    com:
      example: debug
#        demo:

   eureka:
     client:
       service-url:
         defaultZone:  http://127.0.0.1:8090/eureka/, http://127.0.0.1:8060/eureka/,http://127.0.0.1:8070/eureka/
     instance:
   #  每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
       lease-renewal-interval-in-seconds: 1
   #    告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉
       lease-expiration-duration-in-seconds: 2
   spring:
     application:
       name: day1Customer