server:
  port: 8010
age: 18
   eureka:
     client:
       service-url:
         defaultZone:  http://127.0.0.1:8090/eureka/
     instance:
   #  每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
       lease-renewal-interval-in-seconds: 1
   #    告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉
       lease-expiration-duration-in-seconds: 2
spring:
  cloud:
    config:
      discovery:
        service-id: configserver
        enabled: true
      profile: dev
  application:
    name: test


